name: Run Stock Job with Gradle

on:
  schedule:
    - cron: '0,30 12-14 * * 0'

jobs:
  run-batch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle without running tests
        run: ./gradlew build -x test
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

      - name: Run Spring Batch Job
        run: java -jar build/libs/slackStockBotBatch-0.0.1-SNAPSHOT.jar
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
